rp = rp or {}

rp.name = {
	first = {
		"Liam","Noah","Mason","Ethan","Logan","Lucas","Jackson","Aiden","Oliver",
		"Jacob","Elijah","Alexander","James","Benjamin","Jack","Luke","William",
		"Michael","Owen","Daniel","Carter","Gabriel","Henry","Matthew","Wyatt",
		"Caleb","Jayden","Nathan","Ryan","Isaac","Emma","Olivia","Ava","Sophia",
		"Isabella","Mia","Charlotte","Amelia","Emily","Madison","Harper","Abigail",
		"Avery","Lily","Ella","Chloe","Evelyn","Sofia","Aria","Ellie","Aubrey",
		"Scarlett","Zoey","Hannah","Audrey","Grace","Addison","Zoe","Elizabeth","Nora",
	},
	last = {
		"Abramson","Adamson","Adderiy","Addington","Adrian","Albertson","Aldridge",
		"Allford","Alsopp","Anderson",	"Andrews","Archibald","Arnold","Arthurs",
		"Atcheson","Attwood","Audley","Austin","Ayrton","Babcock","Backer","Baldwin",
		"Bargeman","Barnes","Barrington","Bawerman","Becker","Benson","Berrington",
		"Birch","Bishop","Black","Blare","Blomfield","Boolman","Bootman","Bosworth",
		"Bradberry","Bradshaw","Brickman","Brooks","Brown","Bush","Calhoun","Campbell",
		"Carey","Carrington","Carroll","Carter","Chandter","Chapman","Charlson",
		"Chesterton","Clapton","Clifford","Coleman","Conors","Cook","Cramer","Creighton",
		"Croftoon","Crossman","Daniels","Davidson","Day","Dean","Derrick","Dickinson",
		"Dodson","Donaldson","Donovan","Douglas","Dowman","Dutton","Duncan","Dunce",
		"Durham","Dyson","Eddington","Edwards","Ellington","Elmers","Enderson","Erickson",
		"Evans","Faber","Fane","Farmer","Farrell","Ferguson","Finch","Fisher","Fitzgerald",
		"Flannagan","Flatcher","Fleming","Ford","Forman","Forster","Foster","Francis",
		"Fraser","Freeman","Fulton","Galbraith","Gardner","Garrison","Gate","Gerald",
		"Gibbs","Gilbert","Gill","Gilmore","Gilmore","Gimson","Goldman","Goodman",
		"Gustman","Haig","Hailey","Hamphrey","Hancock","Hardman","Harrison","Hawkins",
		"Higgins","Hodges","Hoggarth","Holiday","Holmes","Howard","Jacobson","James",
		"Jeff","Jenkin","Jerome","Johnson","Jones","Keat","Kelly","Kendal","Kennedy",
		"Kennett","Kingsman","Kirk","Laird","Lamberts","Larkins","Lawman","Leapman",
		"Leman","Lewin","Little","Livingston","Longman","MacAdam","MacAlister",
		"MacDonald","Macduff","Macey","Mackenzie","Mansfield","Marlow","Marshman",
		"Mason","Mathews","Mercer","Michaelson","Miers","Miller","Miln","Milton",
		"Molligan","Morrison","Murphy","Nash","Nathan","Neal","Nelson","Nevill",
		"Nicholson","Nyman","Oakman","Ogden","Oldman","Oldridge","Oliver","Osborne",
		"Oswald","Otis","Owen","Page","Palmer","Parkinson","Parson","Pass","Paterson",
		"Peacock","Pearcy","Peterson","Philips","Porter","Quincy","Raleigh","Ralphs",
		"Ramacey","Reynolds","Richards","Roberts","Roger","Russel","Ryder","Salisburry",
		"Salomon","Samuels","Saunder","Shackley","Sheldon","Sherlock","Shorter","Simon",
		"Simpson","Smith","Stanley","Stephen","Stevenson","Sykes","Taft","Taylor","Thomson",
		"Thorndike","Thornton","Timmons","Tracey","Turner","Vance","Vaughan","Wainwright",
		"Walkman","Wallace","Waller","Walter","Ward","Warren","Watson",	"Wayne",
		"Webster","Wesley","White","WifKinson","Winter","Wood","Youmans","Young",
	},
}

rp.name.ProfanityFilter = {
-- #
	"three",
	"four",
	"five",
	"seven",
	"eight",
	"nine",
	"second",
	"third",
	"fourth",
	"fifth",
	"sixth",
	"seventh",
	"ninth",
	"tenth",
-- A
	"ackbar",
	"adolf",
	"akbar",
	"allah",
	"allota",
	"anal",
	"anime",
    "anus",
	"applesauce",
	"ardiem",
    "arse",
    "ass",
	"autist",
	"autistic",
    "adderall",
-- B
    "balls",
    "bastard",
	"bellic",
	"bend",
	"bent",
	"bic",
	"big",
    "bitch",
    "biatch",
	"black",
    "bloody",
	"blow",
	"boi",
    "bollocks",
    "bollok",
    "boner",
	"boners",
	"bonerz",
	"bong",
	"boss",
    "boob",
	"bootie",
	"booty",
	"bra",
	"brownskin",
    "bugger",
    "bum",
    "butt",
-- C
    "castro",
	"chimp",
	"chimpy",
	"chink",
	"chinks",
	"chong",
	"clitoris",
	"cocaine",
    "cock",
	"coderall",
	"condom",
    "coon",
	"cracker",
    "crap",
    "cunt",
    "cum",
-- D
    "daboss",
	"daddy",
	"dahboss",
	"damn",
	"dark",
	"darth",
	"ddos",
	"derp",
	"dev",
	"dic",
    "dildo",
	"dis",
	"doctor",
	"dover",
	"downie",
	"drumpf",
	"dude",
    "dyke",
-- E
	"ebola",
	"egg",
-- F
    "fag",
	"fagot",
    "fat",
	"fatty",
	"feck",
	"feet",
    "fellate",
    "fellatio",
    "felching",
	"fetus",
	"fist",
	"first",
	"foot",
	"foreskin",
    "fuck",
	"fucker",
    "fudgepacker",
	"fuhrer",
    "flange",
-- G
    "gae",
	"gay",
	"grandpa",
	"grandma",
	"granny",
	"grimes",
	"god",
	"goff",
	"gook",
	"goddamn",
	"gurra",
	"gurrazor",
-- H
	"harambe",
    "hell",
	"hentai",
	"himmler",
	"hitler",
    "homo",
	"hunt",
-- I
	"idk",
-- J
    "jedi",
	"jerk",
	"jesus",
	"jew",
	"jewy",
    "jizz",
	"jong",
	"jongil",
	"jongun",
-- K
    "kek",
	"kok",
	"knobend",
    "knob",
-- L
    "labia",
	"last",
	"lastname",
	"little",
	"lil",
    "lmao",
    "lmfao",
	"long",
	"lord",
-- M
	"mama",
	"man",
	"mao",
	"mcfaggot",
	"mcnigga",
	"mcnigger",
	"mcnigbig",
	"meme",
	"mister",
	"money",
	"monolith",
	"motherfucker",
	"monkey",
	"mrs",
    "muff",
	"muslim",
	"mungus",
-- N
	"nazi",
	"negan",
	"neger",
	"negus",
	"nig",
	"nigg",
	"nigger",
	"ninja",
	"normus",
	"normous",
-- O
    "obama",
	"old",
	"omg",
	"osama",
	"over",
-- P
    "papa",
	"pee",
	"penis",
	"penls",
	"pepe",
    "piss",
	"pissy",
	"poo",
	"pony",
    "porn",
	"pound",
    "prick",
	"princess",
    "pube",
    "pussy",
	"putin",
-- Q
    "queer",
-- R
	"rasputin",
	"reich",
-- S
	"samurai",
	"satan",
	"scrotum",
	"schlong",
	"server",
    "sex",
	"sith",
	"size",
	"sherlock",
	"shrek",
    "shit",
	"shitter",
	"shitty",
	"short",
	"shorty",
    "slut",
	"slave",
    "smegma",
	"snape",
	"snowden",
	"soviet",
	"spartan",
	"spongebob",
	"squidward",
	"stallone",
	"stalin",
	"stoner",
	"stroker",
	"sydrome",
	"semen",
-- T
    "terrorist",
	"testicles",
	"tit",
	"titties",
	"tits",
	"toff",
    "tosser",
	"trump",
	"trummp",
    "turd",
    "twat",
	"tyrone",
-- U
	"ugly",
	"uncle",
-- V
    "vader",
	"vag",
	"vagina",
	"vape",
-- W
    "weed",
	"weiner",
    "wank",
	"wanker",
	"wick",
	"willie",
	"willy",
    "whore",
	"wonka",
    "wtf"
}

function rp.name.TextContainsProfain( sText, tCustomProfanityFilter )
    for _, sWord in ipairs( tCustomProfanityFilter and tCustomProfanityFilter or rp.name.ProfanityFilter ) do
        if string.find( sText, sWord ) then
            return true
        end
    end

    return false
end

function rp.name.ValidateName( name, lastname )

    if lastname then
        return rp.name.ValidateName( name ) and rp.name.ValidateName( lastname )
    end

    if not name then return false end

    name = string.Trim(name)
    name = string.lower(name)

    -- Check name size
    if string.len(name) < 3 or string.len(name) >= 16 then
        return false
    end

    -- Check name for invalid characters
    -- if string.match( name, "%a" ) != nil then
    --     return false
    -- end

    -- Check name for profanity
    if rp.name.TextContainsProfain(name) then return false end

    return true
end