rp.AddTerm('NotEnoughTime', 'У вас отыграно слишком мало времени!')
rp.AddTerm('FireEx', 'Вы получили #$ за тушение пожара!')
rp.AddTerm('AxeNoFire', 'Для того чтобы дверь открылась, нужно чтобы было возгорание за ней или на ней!') 
rp.AddTerm('HWGetMoney', 'Вы получили 30 кредитов!')
rp.AddTerm('Cantplant', 'Здесь гриб не приживётся.')
rp.AddTerm('LimiteMush', 'Достигнуто максимальное количество грибов')
rp.AddTerm('DataNotLoaded', 'ВАШИ ДАННЫЕ НЕ ЗАГРУЖЕНЫ. ПОЖАЛУЙСТА, ПОДОЖДИТЕ. ЕСЛИ ЭТО СЛУЧИТСЯ СНОВА, ПОЖАЛУЙСТА, СООБЩИТЕ НАМ ОБ ЭТОМ!')
rp.AddTerm('PleaseWaitX', 'Пожалуйста, подождите # секунд для этого.')
rp.AddTerm('+Money', '+$#')
rp.AddTerm('-Money', '-$#')
rp.AddTerm('InvalidArg', 'Недействительный аргумент.')
rp.AddTerm('CantFindPlayer', 'Невозможно найти игрока #.')
rp.AddTerm('CannotAfford', 'У Вас не хватает денег!')
rp.AddTerm('NeedVIP', 'Вам нужен VIP статус! Напишите /upgrades чтобы купить.')
rp.AddTerm('NeedToWait', 'Вам нужно подождать # секунд чтобы сделать это!')
rp.AddTerm('ChangeJob', '# теперь # #.')
rp.AddTerm('CannotChangeJob', 'Вы не можете сменить работу в течении #!')
rp.AddTerm('ChangeName', '# изменил имя на #')
rp.AddTerm('Payday', 'Зарплата! Вы получили $#.')
rp.AddTerm('PaydayTax', 'Зарплата! Вы получили $# - $# налог.')
rp.AddTerm('PayDayUnemployed', 'Вы не получили зарплату, потому что Вы - безработный!')
rp.AddTerm('PayDayMissed', 'Вы арестованы и не получили зарплату!')
rp.AddTerm('NotAllowedInSpawn', '# недопустимо на спавне!')
rp.AddTerm('LostKarma', 'Вы потеряли # очков Кармы, за #!')
rp.AddTerm('LostKarmaNR', 'Вы потеряли # очков Кармы.')
rp.AddTerm('LostKarmaDrugs', 'Вы потеряли # очков Кармы, за использование наркотиков.')
rp.AddTerm('SpawnPropsSoFast', 'Пожалуйста, спавните пропы не так быстро.')
rp.AddTerm('RPNameShort', 'RP имя должно быть длиннее # символов.')
rp.AddTerm('RPNameLong', 'RP имя должно быть короче # символов.')
rp.AddTerm('CannotRPName', 'Вы не можете изменить RP имя.')
rp.AddTerm('RPNameUnallowed', 'Это имя содержит недоступные символы (#).')
rp.AddTerm('SteamRPNameTaken', 'Ваше Steam-Имя уже используется кем-то, поэтому мы поставили "1" после Вашего имени.')
rp.AddTerm('RPNameTaken', 'Это RP имя уже взято ')
rp.AddTerm('EscapeDemotion', 'Вы пытаетесь избежать увольнения. У Вас не получилось, и Вы были уволены.')
rp.AddTerm('PlayerDemoted', '# был уволен.')
rp.AddTerm('PlayerNotDemoted', '# не был уволен.')
rp.AddTerm('DemotionStarted', '# начал голосование на увольнение #.')
rp.AddTerm('DemotionReason', 'Пожалуйста, укажите причину увольнения.')
rp.AddTerm('DemoteReasonLong', 'Ваша причина увольнения должна быть длиннее # characters.')
rp.AddTerm('DemoteSelf', 'Вы не можете уволить себя.')
rp.AddTerm('UnableToDemote', 'Вы не можете начать голосование.')
rp.AddTerm('ChannelLimit', 'Выберите канал от 0 до 100.')
rp.AddTerm('ChannelSet', 'Канал установлен на #.')
rp.AddTerm('ChannelNotSet', 'Вы не выставили свой канал!')
rp.AddTerm('GiveMoneyLimit', 'Вы не можете передать меньше чем $1.')
rp.AddTerm('DropMoneyLimit', 'Вы не можете выбросить меньше $1.')
rp.AddTerm('ChequeArg1', 'Недействительный аргумент #1: получатель.')
rp.AddTerm('ChequeArg2', 'Недействительный аргумент #2: количество.')
rp.AddTerm('PlayerGaveCash', '# дал Вам #.')
rp.AddTerm('YouGaveCash', 'Вы дали # #.')
rp.AddTerm('MustLookAtPlayer', 'Вы должны смотреть на игрока.')
rp.AddTerm('HoesProfit', 'Ты заработал $100 со своей шлюхи.')
rp.AddTerm('CannotAffordHoe', '# не может позволить себе Ваши услуги!')
rp.AddTerm('YouCannotAffordHoe', 'Вы не можете позволить себе услуги #!')
rp.AddTerm('GetCloser', 'Должен быть ближе к своей цели!')
rp.AddTerm('YouAreDead', 'Вы мертвы!')
rp.AddTerm('NotAHoe', 'Вы не проститутка.')
rp.AddTerm('NPCsDontFuck', 'Вы не можете заняться сексом с NPC.')
rp.AddTerm('TargetFrozen', 'Ваша цель заморожена.')
rp.AddTerm('WaitingForAnswer', 'В ожидании ответа.')
rp.AddTerm('TargetWontFuck', 'Ваша цель не желает заниматься сексом.')
rp.AddTerm('TargetTooFar', 'Ваша цель слишком далеко.')
rp.AddTerm('HoeTooFar', 'Ваша шлюха слишком далеко.')
rp.AddTerm('+FuckCostPimp', '+$# - $100 (доля сутенера)')
rp.AddTerm('Warranted', '#\nПричина: #\nОрдер на: #.')
rp.AddTerm('Wanted', '# \nПричина: #\nВыдал ордер: #.')
rp.AddTerm('Arrested', '# арестован.')
rp.AddTerm('UnArrested', '# выпущен из тюрьмы.')
rp.AddTerm('DoorLocked', 'Закрыто!')
rp.AddTerm('DoorUnlocked', 'Открыто!')
rp.AddTerm('MaxDoors', 'Вы достигли максимального количества купленных дверей!')
rp.AddTerm('DoorBought', 'Вы оплатили аренду за #.')
rp.AddTerm('DoorOwnerAdded', '# был добавлен в Вашу дверь.')
rp.AddTerm('DoorOwnerAddedYou', '# добавил Вас в свою дверь.')
rp.AddTerm('DoorOwnerRemoved', '# был удалён из Вашей двери.')
rp.AddTerm('DoorOwnerRemovedYou', '# удалил из своей двери.')
rp.AddTerm('DoorSold', 'Вы продали дверь за #.')
rp.AddTerm('DoorTitleSet', 'Название двери установленно .')
rp.AddTerm('OrgDoorEnabled', 'Владение организации разрешено')
rp.AddTerm('OrgDoorDisabled', 'Владение организации запрещено .')
rp.AddTerm('NoDoors', 'У Вас нет дверей на продажу.')
rp.AddTerm('DoorsSold', 'Вы продали # дверь за #.')
rp.AddTerm('EventEnded', '# Ивент закончился.')
rp.AddTerm('OrgDisbanded', '# был распущен!')
rp.AddTerm('OrgPlayerKicked', '# кикнут из организации #.')
rp.AddTerm('OrgPlayerYoureKicked', 'Вы были кикнуты из организации #.')
rp.AddTerm('OrgMustLeaveFirst', 'Вам нужно покинуть организацию чтобы создать новую.')
rp.AddTerm('OrgNameShort', 'Пожалуйста, сделайте название своей организации длиннее чем 2 буквы.')
rp.AddTerm('OrgNameLong', 'Пожалуйста, сделайте название своей организации короче чем чем 20 букв.')
rp.AddTerm('OrgNameTaken', 'Это имя уже занято. Пожалуйста выберите другое!')
rp.AddTerm('OrgCannotAffort', 'Вы не можете позволить себе создать организацию.')
rp.AddTerm('OrgCreated', 'Вы успешно создали свою организацию.')
rp.AddTerm('OrgMOTDChanged', 'Вы изменили вашу организацию MoTD.')
rp.AddTerm('OrgColorChanged', 'Вы изменили цвет организации.')
rp.AddTerm('OrgPlayerQuit', '# вышел из #!')
rp.AddTerm('OrgMemberLimit', 'Вы достигли максимального количество # членов в организации!')
rp.AddTerm('OrgMemberJoined', '# присоединился к #.')
rp.AddTerm('MustBeMayorSetLaws', 'Вы должны быть Мэром чтобы установить закон!')
rp.AddTerm('MustBeMayorResetLaws', 'Вы должны быть Мэром чтобы сбросить законы!')
rp.AddTerm('LotteryTax', 'Вы заработали # в лотереи.')
rp.AddTerm('LotteryWinner', '# выйграл # в лотерее!')
rp.AddTerm('NoLottery', 'Никто не учавствовал в лотерее, поэтому Ваши деньги были возвращены.')
rp.AddTerm('NoLotteryTax', 'Вы заработали $0 в лотереи потому, что никто не учавствовал.')
rp.AddTerm('NotInLottery', 'Вы не учавствуете в лотерее.')
rp.AddTerm('InLottery', 'Вы учавствуете в лотерее за  #.')
rp.AddTerm('NoLotteryAll', 'Никто не учавствует в лотерее.')
rp.AddTerm('CannotLottery', 'Вы не можешь учавствовать в лотерее прямо сейчас.')
rp.AddTerm('LottoCooldown', 'Пожалуйста, подождите # секунд чтобы начать лотерею')
rp.AddTerm('LottoCost', 'Пожалуйста, установ цену на вход ($#-$#).')
rp.AddTerm('LotteryStarted', 'Лотерея началась!')
rp.AddTerm('CannotLockdown', 'Комендантский час сейчас недоступен.')
rp.AddTerm('LockdownStarted', 'Мэр объявил комендантский час, вернитесь домой!')
rp.AddTerm('CannotUnlockdown', 'Вы не можете запустить комендантский час сейчас.')
rp.AddTerm('LockdownEnded', 'Комендантский час окончен.')
rp.AddTerm('WarrantExpired', 'Ваш ордер просрочен.')
rp.AddTerm('WantedPlayerNotFound', '# не найден!')
rp.AddTerm('PlayerAlreadyWanted', '# Уже разыскивается!')
rp.AddTerm('PlayerAlreadyWarranted', '# Уже есть ордер!')
rp.AddTerm('PlayerNotWanted', '# не разыскивается!')
rp.AddTerm('PlayerNotWarranted', 'На # нет ордера!')
rp.AddTerm('WarrantRequestAcc', 'Ваш ордер одобрен.')
rp.AddTerm('WarrantRequestDen', 'Ваш ордер был отклонён.')
rp.AddTerm('HitComplete', 'Заказ на # выполнен.')
rp.AddTerm('YourHitComplete', 'Вы были убит наёмным убийцей.')
rp.AddTerm('HitTargetInvalid', 'Вы должны выбрать правильную цель!')
rp.AddTerm('CantHitYourself', 'Вы не можете заказать себя!')
rp.AddTerm('CantHitHitman', 'Вы не можете заказать Наёмника!')
rp.AddTerm('CantPlaceHit', 'Наёмник не может делать заказ!')
rp.AddTerm('HitPriceLimit', 'Цены на заказ должны быть от # и до #.')
rp.AddTerm('HitTimer', 'Вы не можете нанести удар в течении # секунд.')
rp.AddTerm('MultiHit', 'Вы не можете заказать одного и того же человека так часто!')
rp.AddTerm('BountyIncrease', 'Вы увеличили вознаграждение за # на #.')
rp.AddTerm('HitPlaced', 'Вы сделали заказ на # за #.')
rp.AddTerm('HitmanFailed', 'Вы потерпели неудачу в качестве киллера!')
rp.AddTerm('EmployeeChangedJob', 'Ваш наниматель изменил работу!')
rp.AddTerm('EmployeeChangedJobYou', 'Ваш контракт был отменён потому, что вы сменили работу!')
rp.AddTerm('EmployeeDied', 'Ваша цель умерла!')
rp.AddTerm('EmployeeDiedYou', 'Ваш контракт был отменён потому что, Вы - умерли!')
rp.AddTerm('EmployerDied', 'Ваш наниматель умер!')
rp.AddTerm('EmployerDiedYou', 'Ваш работник уволен потому, что вы умерли.')
rp.AddTerm('EmployeeLeft', 'Ваша цель отключилась!')
rp.AddTerm('EmployerLeft', 'Ваш наниматель отключился!')
rp.AddTerm('PlayerNotHirable', '# не может быть нанят.')
rp.AddTerm('EmployeeTriedEmploying', 'В данный момент Вы ищете работу. Вы не можете нанять рабочего !')
rp.AddTerm('HasEmployee', 'Вы уже наёмный работник!')
rp.AddTerm('AlreadyEmployed', 'Вы уже нанят!')
rp.AddTerm('CannotAffordEmployee', 'Вы не можете нанять!')
rp.AddTerm('EmployRequestSent', '# отправил Вам запрос на найм.')
rp.AddTerm('YouHired', 'Вас нанял # для #.')
rp.AddTerm('YouAreHired', '# нанял Вас для #.')
rp.AddTerm('EmployRequestDen', '# отменил вашу заявку на работу.')
rp.AddTerm('EmployeeFired', 'Вы уволены #.')
rp.AddTerm('EmployeeFiredYou', '# Уволил вас!')
rp.AddTerm('EmployeeQuit', '#Вышел с работы вместе с вами!')
rp.AddTerm('EmployeeQuitYou', 'Вы ушли с работы #.')
rp.AddTerm('CannotTool', 'Недостаточно прав использовать "#" инструмент!')
rp.AddTerm('DupeRestrictedEnts', 'Вы не можете создавать дупликаты этих объектов!')
rp.AddTerm('WhitelistFull', ' Белый Список полон #/750')
rp.AddTerm('CacheFull', 'Модель Кэша заполнена #/100!')
rp.AddTerm('PropWhitelisted', '# добавлен в Белый Список #.')
rp.AddTerm('PropBlacklisted', '# был помещен в Черный Список #.')
rp.AddTerm('PPTargNotFound', 'Цель не найдена !')
rp.AddTerm('UnsharedPropsYou', 'Вы отменили доступ к своим пропам для #.')
rp.AddTerm('UnsharedProps', '# отменил вам доступ к своим пропам.')
rp.AddTerm('SharedPropsYou', 'Вы открыли доступ к своим пропам для  #.')
rp.AddTerm('SharedProps', '# Предоставил доступ к своим пропам для вас.')
rp.AddTerm('PPGroupSet', '# был добавлен в группу # by #.')
rp.AddTerm('PropNotWhitelisted', '# не в вайтлисте!')
rp.AddTerm('NoPMResponder', 'Там никого нет чтобы ответить')
rp.AddTerm('CannotDestroyWeapon', 'Вы не можете уничтожить это оружие!')
rp.AddTerm('YourEntDestroyed', 'Ваше # было уничтожено!')
rp.AddTerm('InvalidURL', 'не правильный URL!')
rp.AddTerm('VideoFailed', 'Не удалось загрузить видео: #.')
rp.AddTerm('FoodLimitReached', 'Вы достигли лимита еды!')
rp.AddTerm('BoughtFoodProduction', 'Вы заплатили # за продукты.')
rp.AddTerm('SoldFoodNoProf', 'Вы продали еду и не получили денег, но заработали 3 Кармы.')
rp.AddTerm('SoldFood', 'Вы продали еду и заработали #')
rp.AddTerm('BoughtFood', 'Вы купили еду для #.')
rp.AddTerm('ThereIsACook', 'Есть повар. Вы не можете сделать этого!')
rp.AddTerm('EmptyShipment', 'Там нет товаров.')
rp.AddTerm('GCMessageLimit', 'Ваше сообщение должно быть больше чем 1 буква!')
rp.AddTerm('CantSuicideJail', 'Вы не можете покончить жизнь самоубийством в тюрьме.')
rp.AddTerm('CantSuicideWanted', 'Вы не можете покончить жизнь самоубийством пока вы в розыске .')
rp.AddTerm('CantSuicideFrozen', 'Вы не можете покончить жизнь самоубийством пока вы freeze.')
rp.AddTerm('CantSuicideLiveFor', 'Вам ещё долго жить!')
rp.AddTerm('YouSuicided', 'Вы опозорили свою семью!')
rp.AddTerm('CantPurchaseUpgrade', 'Вы не можете купить это. #')
rp.AddTerm('RPItemBought', 'Вы купили # за #.')
rp.AddTerm('CantAdminCleanup', 'Вы не можете использовать админскую очистку!')
rp.AddTerm('MayorHasDied', 'Мэр мёртв!')
rp.AddTerm('YouWereBailed', '# освободил тебя из тюрьмы!')
rp.AddTerm('ArmorLabProfit', 'Вы заработали $# из своей armor lab.')
rp.AddTerm('BoughtArmor', 'Вы купили Броне-Лабу за $#.')
rp.AddTerm('ArmorLabExploded', 'Ваша Броне-Лаба взорвалась!')
rp.AddTerm('ChequeFound', 'Вы нашёли # в чеке записанном на тебя #.')
rp.AddTerm('ChequeMadeTo', '"Этот чек сделан к  #.')
rp.AddTerm('ChequeTorn', 'Вы разорвали чек.')
rp.AddTerm('MoneyFound', 'Вы нашли $#!')
rp.AddTerm('MustBeHobo', 'Только бомжи могут это делать!')
rp.AddTerm('AlreadyDisguised', 'Вы уже замаскированы!')
rp.AddTerm('GunLicenseActive', 'Вы активировали лицензию на оружие.')
rp.AddTerm('YouGotAIDS', 'Вы заразились сифилисом.')
rp.AddTerm('YouGotHerpes', 'Вы заразились герпесом от иглы.')
rp.AddTerm('STDCured', 'Вы вылечились от сифилиса.')
rp.AddTerm('NowDisguised', 'Вы замаскированы как #.')
rp.AddTerm('NowDisguisedTime', 'Вы замаскированы как # на  #.')
rp.AddTerm('DisguiseWorn', 'Ваша маскировка закончилась.')
rp.AddTerm('DisguiseLimit', 'Вы не можете маскироваться ещё # минут.')
rp.AddTerm('MedLabProfit', 'Вы заработали $# на своей Мед-Лабу.')
rp.AddTerm('BoughtHealth', 'Вы купили здоровье за $#.')
rp.AddTerm('MedLabExploded', 'Ваша Мед-Лаба взорвалась!')
rp.AddTerm('KeypadControlsX', 'Этот кейпад контролирует # объект.')
rp.AddTerm('EntityControlledByX', 'Этот объект под контролем  # кейпада.')
rp.AddTerm('VoteAlone', 'Вы выйграли выборы поскольку были единственным кандидатом.')
rp.AddTerm('BannedFromJob', 'В настоящее время эта работа недоступна для вас.')
rp.AddTerm('VotedTooSoon', 'Пожалуйста, подождите # секунд чтобы начать голосование.')
rp.AddTerm('AlreadyThisJob', 'Вы уже на этой работе!')
rp.AddTerm('JobLimit', 'Лимит команды достигнут.')
rp.AddTerm('RegisteredForVote', 'Вы зарегистрированы на предстоящие выборы!')
rp.AddTerm('AlreadyVoting', 'Выборы уже начались. Вы опоздали!')
rp.AddTerm('JobNeedsAdmin', 'Вы должны быть moderator+ для этой работы.')
rp.AddTerm('JobNeedsSA', 'Вы должны быть SA+ для этой работы.')
rp.AddTerm('JobNeedsBanned', 'Ты должен быть забанен на сервере чтобы получить этот класс')
rp.AddTerm('IncorrectJob', 'У вас не та работа чтобы сделать это!')
rp.AddTerm('VoteStarted', 'Голосование создано.')
rp.AddTerm('CannotJob', 'Вы не можете изменить работу прямо сейчас.')
rp.AddTerm('JobLenShort', 'Название работы должно быть больше чем # буква.')
rp.AddTerm('JobLenLong', 'Название работы должно быть меньше чем  # букв.')
rp.AddTerm('CannotPurchaseItem', 'Вы не допущены к покупке этого предмета.')
rp.AddTerm('ItemLimit', 'Вы достигли # лимит.')
rp.AddTerm('ItemUnavailable', 'Эта вещь недоступна.')
rp.AddTerm('UnableToItem', 'Вы не в состоянии купить эту вещь.')
rp.AddTerm('ShipmentCooldown', 'Подождите прежде чем спавнить товар.')
rp.AddTerm('MedicExists', 'Вы не можете купить HP потому, что есть медик.')
rp.AddTerm('HealthIsFull', 'Ваше здоровье уже полное!')
rp.AddTerm('CannotDropWeapon', 'Вы не можете выкинуть это оружие!')
rp.AddTerm('LookAtEntity', 'Вы дожны смотреть на объект!')
rp.AddTerm('CannotSetPrice', 'Вы не можете установить цену на этот объект !')
rp.AddTerm('AnalProlapse', 'Вы перенапрягли анус и умерли от пролапса.')
rp.AddTerm('NoMorePoo', 'У тебя больше нет каках !')
rp.AddTerm('NotARapist', 'Вы не насильник.')
rp.AddTerm('RapeNPC', 'Вы не можете насиловать NPC.')
rp.AddTerm('RapeFailed', 'Попытка изнасилования провалена!')
rp.AddTerm('RapeAttempted', 'Кто-то пытается вторгнуться в вашу жопу.')
rp.AddTerm('Raped', 'Вас изнасиловал #, засадив вам прямо в зад.')
rp.AddTerm('YouAreRaped', 'Кто-то вторгается в ваш зад.')
rp.AddTerm('AnalProlapseShort', 'Вы умерли от анального пролапса.')
rp.AddTerm('DickFellOff', 'Ваш член отвалился.')
rp.AddTerm('CannotVote', 'Вы не можете голосовать.')
rp.AddTerm('CantDoThis', 'Вы не можете сделать это.')
rp.AddTerm('BaitingRule', 'Это не по правилам.')
rp.AddTerm('FoundNothing', 'Вы ничего не нашли.')
rp.AddTerm('RobberyAttempt', 'Вы чувствуете лёгкое движение в кармане.')
rp.AddTerm('RobberyFailed', 'Ограбление провалено!')
rp.AddTerm('YouRobbed', 'Вы украли $#!')
rp.AddTerm('YouAreRobbed', 'Ваш карман облегчился.')
rp.AddTerm('NoteUpdated', 'Текст не обновлен.')
rp.AddTerm('USENote', 'Нажмите использовать чтобы редактировать текст.')
rp.AddTerm('OrgYouAreStuck', 'Вы застряли! >:)')
rp.AddTerm('OrgYourRank', '# установил ваш ранг \'#\'.')
rp.AddTerm('OrgSetRank', '# добавлен \'#\'.')
rp.AddTerm('OrgUnknownRank', 'неизвестный ранг \'#\'.')
rp.AddTerm('OrgRankRename', 'Ранг \'#\' переименован в \'#\'.')
rp.AddTerm('OrgReorderLimit', 'Вы не можете изменить Высший и Низший ранги.')
rp.AddTerm('OrgRankUpdated', 'Ранг \'#\' обновлен.')
rp.AddTerm('OrgMaxRanks', 'Максимальный ранг достигнут.')
rp.AddTerm('OrgRankCreated', 'Ранг \'#\' Создан.')
rp.AddTerm('OrgDeleteLimit', 'Вы не можете удалить высший и низший ранг.')
rp.AddTerm('OrgRankDelete', 'Ранг \'#\' удалён.')
rp.AddTerm('OrgBannerUpdated', 'Банер обновлён.')
rp.AddTerm('FadeDoorCreated', 'Fading door создан.')
rp.AddTerm('FadeDoorCreatedExtra', 'Fading door создан. Теперь, правый клик чтобы создать кейпад.')
rp.AddTerm('InvalidPassword', 'неверный пароль!')
rp.AddTerm('KeypadHoldLength', 'Время удержание должно быть не менее # секунд.')
rp.AddTerm('KeypadCreated', 'Кейпад создан.')
rp.AddTerm('SboxPropLimit', 'Вы достигли лимита пропов!')
rp.AddTerm('SboxXLimit', 'Вы достигли # лимит')
-- Entities folder
rp.AddTerm('ArcadeMachineUse', 'Приготовьтесь к игре!')
rp.AddTerm('PlayerNotInJail', '# не в тюрьме.')
rp.AddTerm('PlayerFuckedBailing', 'Ты придурок, копы у тебя на хвосте!')
rp.AddTerm('PlayerBailedPlayer', '# заплатил за вас выкуп #.')
rp.AddTerm('PlayerTookDonationBox', 'Вы взяли #.')
rp.AddTerm('YouDontOwnThis', 'Вы не владеете этим!')
rp.AddTerm('PlayerReceivedDonationBox', 'Кто-то пожертвовал # в вашу коробку для пожертвования.')
rp.AddTerm('DrugLabExploded', 'Ваша нарко-лаборатория взорвалась!')
rp.AddTerm('PlayerNotWanted', 'Этот игрок не разыскивается!')
rp.AddTerm('PlayerTookMoneyBasket', 'Вы взяли #.')
rp.AddTerm('PrinterIsFull', 'Этот принтер полон чернилами!')
rp.AddTerm('PrinterRefilled', 'Вы заправили принтер за #.')
rp.AddTerm('PrinterExploded', 'Ваш принтер взорвался!')
rp.AddTerm('PlayerSoldDrugs', 'Вы продали # за #.')
-- Weapons folder
rp.AddTerm('ArrestBatonBonus', 'Вы заработали # бонус за уничтожение нелегального объекта.')
rp.AddTerm('ArrestBatonArrested', 'Вас арестовал #.')
rp.AddTerm('ArrestBatonYouArrested', 'Вы арестовали #.')
rp.AddTerm('PlayerRangDoorbell', 'Кто-то звонит в ваш дверной звонок.')
rp.AddTerm('KeysCooldown', 'Пожалуйста, подождите прежде чем закрывать дверь')
rp.AddTerm('UnarrestBatonTarg', 'Вас выпустил из тюрьмы #.')
rp.AddTerm('UnarrestBatonOwn', 'Вы освобождены #.')
rp.AddTerm('RiotShieldInSpawn', 'Пожалуста, покиньте спавн чтобы использовать этот щит!')
rp.AddTerm('HatPurchased', 'Вы заплатили # для #.')
rp.AddTerm('HatEquipped', 'Аксессуар надет!')
rp.AddTerm('HatRemoved', 'Шапка снята!')
rp.AddTerm('BURGHungerImmune', 'У вас имунитет к голоду пока твы не умрёте!')
rp.AddTerm('BURGNotPeople', 'Глупый бургер, бургер не человек!')

rp.AddTerm('WantedReasons', {'Убийство', 'Нелегальное оружие', 'Нанесение увечий', 'Нелегальные предметы'})

rp.AddTerm('KarmaAdeed', 'Господь отпустил ваши грехи!')
rp.AddTerm('KarmaCooldown', 'Вашу праведность стоило бы доказать делом!')
rp.AddTerm('GoodKarmaGain', 'Последнее время вы вели праведный образ жизни и получили # кармы!')


rp.AddTerm('nu.vehicleNotOwned', 'Вы не являетесь владельцем этого транспортного средства!')
rp.AddTerm('nu.vehicleSold', 'Вы продали # за $# !')
rp.AddTerm('nu.vehicleBought', 'Вы купили # за $#!')
rp.AddTerm('nu.vehicleReturned',  'Вы вернули свою машину!')
rp.AddTerm('nu.returnVehicleFirst', 'Вам нужно вернуть своё транспортное средство прежде чем брать другое!')
rp.AddTerm('nu.vehicleRestricted', 'Вы не можете спавнить этот автомобиль')
rp.AddTerm('nu.noMoneyForFee', 'У вас недостаточно средств, чтобы заплатить за спавн автомобиля.')
rp.AddTerm('nu.spawnVehicleFeeMsg', 'Вы заплатили $# за спавн #')
rp.AddTerm('nu.vehicleGranted', 'Вам дали автомобиль: # на #!')
rp.AddTerm('nu.vehicleRevoked', 'Вы забрали у # право на #!')
rp.AddTerm('nu.vehiclesForceReturned', 'Все ваши машины были возвращены #!')
rp.AddTerm('nu.alreadyOwned', 'У вас есть уже этот автомобиль!')
rp.AddTerm('nu.notEnoughMoney', 'У вас нет денег для того, чтобы купить этот автомобиль!')
rp.AddTerm('nu.spawn', 'Доставить')
rp.AddTerm('nu.nu.return', 'Вернуть')
rp.AddTerm('nu.purchase', 'Купить')
rp.AddTerm('nu.sell', 'Продать')
rp.AddTerm('nu.manager', 'Менеджер')
rp.AddTerm('nu.mods', 'Тюннинг')
rp.AddTerm('nu.paint', 'Цвет')
rp.AddTerm('nu.selectVehicleFirst', 'Сперва выберите автомобиль!')
rp.AddTerm('nu.saleEndsIn', 'Продам за: #')
rp.AddTerm('nu.shop','Магазин')
rp.AddTerm('nu.searchByTags', 'Поиск..')

rp.AddTerm('BankReady', 'В банк завезли деньги, интересно, попробует ли их кто-то украсть...')
rp.AddTerm('BankRobberyStarted', 'Грабители ворвались в хранилище банка, остановите их!')
rp.AddTerm('BankFillingCases', 'Началось наполнение кейсов деньгами, отнеси их к машине, когда посчитаешь, что тебе хватит!')
rp.AddTerm('BankRobberyInProgress', 'Банк грабят, немедленно остановите грабителей!')
rp.AddTerm('BankBringCases', 'Скорее тащи кейсы в машину, я сваливаю через # секунд!')
rp.AddTerm('BankRobberyEnd', 'Всё, я ухеал. Ты упустил свой шанс.')
rp.AddTerm('BankCaseReturnReward', 'Ты вернул деньги в банк и получил $# и # кармы!')
rp.AddTerm('BankCaseStealReward', 'Отлично, вот твои $#!')
rp.AddTerm('BankRobbersWon', 'Ограбление закончено, грабители одержали победу')
rp.AddTerm('BankDraw', 'Ограбление закночилось ничьей')
rp.AddTerm('BankPoliceWon', 'Ограбление закончено, полиция победила бандитов')
rp.AddTerm('BankBringCaseToBank', 'Отнеси кейс обратно в банк, если хочешь получить награду!')
rp.AddTerm('BankBringCaseToCar', 'Тащи кейс к машине, если хочешь получить награду!')
rp.AddTerm('BankProtectCar', 'Не дай грабителям отнести кейс к машине!')
rp.AddTerm('NotAllowedInBank', '# не разрешен в банке!')

