-- Misc
-- ID пиши с маленькой буквы! (perma_ammo)
-- rp.shop.Add('Сумка с патронами', 'perma_ammo')
--   :SetCat('Основное')
--   :SetDesc('При каждом возраждении вам выдаётся сумка с 60 патронами каждого вида.\nМожно докупать.')
--   :SetPrice(75)
--   :SetStackable(true)
--   :SetOnBuy(function(self, pl)
--     pl:GiveAmmos(pl:GetUpgradeCount('perma_ammo')*60, true)
--   end)

rp.shop.GlobalDiscount = 0 -- 0.7 - 70% от указанных цен. 0 - отключить скидку

rp.shop.Add('+1 Уровень', 'levelup1')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 1.')
  :SetPrice(25)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(1)
  end)

  rp.shop.Add('+10 Уровней', 'levelup10')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 10.')
  :SetPrice(200)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(10)
  end)

  rp.shop.Add('+20 Уровней', 'levelup20')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 20.')
  :SetPrice(350)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(20)
  end)

  rp.shop.Add('+40 Уровней', 'levelup40')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 40.')
  :SetPrice(600)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(40)
  end)

  rp.shop.Add('+50 Уровней', 'levelup50')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 50.')
  :SetPrice(750)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(50)
  end)

   rp.shop.Add('+60 Уровней', 'levelup60')
  :SetCat('Основное')
  :SetDesc('Увеличить свой уровень на 60.')
  :SetPrice(900)
  :SetOnBuy(function(self, pl)
    pl:AddLevel(60)
  end)

  rp.shop.Add('Пропуск для компендиума', 'CompendiumPass')
  :SetCat('Компендиум')
  :SetDesc([[
    Данный пропуск дает вам доступ к особой линии наград компендиума.
    Вам сразу откроется доступ ко всем наградам подходящим по уровню компендиума!
  ]])
  :SetPrice(200)
  :SetCanBuy(function(self, pl)
    return !(pl:GetUpgradeCount('CompendiumPass') >= 1), 'Вы уже имеете пропуск!'
  end)
  :SetOnBuy(function(self, pl)
    pl:SetNVar('HasCompUpgrade', true, NETWORK_PROTOCOL_PRIVATE)
  end)

  rp.shop.Add('+1 Уровень', 'compendiumlevelup1')
  :SetCat('Компендиум')
  :SetDesc('Увеличить уровень компендиума на 1.')
  :SetPrice(19)
  :SetOnBuy(function(self, pl)
    pl:AddCompendiumLevel(1)
  end)

  rp.shop.Add('+5 Уровней', 'compendiumlevelup5')
    :SetCat('Компендиум')
    :SetDesc('Увеличить уровень компендиума на 5.')
    :SetPrice(49)
    :SetOnBuy(function(self, pl)
      pl:AddCompendiumLevel(5)
    end)

  rp.shop.Add('+10 Уровней', 'compendiumlevelup10')
    :SetCat('Компендиум')
    :SetDesc('Увеличить уровень компендиума на 10.')
    :SetPrice(99)
    :SetOnBuy(function(self, pl)
      pl:AddCompendiumLevel(10)
    end)


  rp.shop.Add('+20 Уровней', 'compendiumlevelup20')
    :SetCat('Компендиум')
    :SetDesc('Увеличить уровень компендиума на 20.')
    :SetPrice(199)
    :SetOnBuy(function(self, pl)
      pl:AddCompendiumLevel(20)
    end)


  rp.shop.Add('+50 Уровней', 'compendiumlevelup50')
    :SetCat('Компендиум')
    :SetDesc('Увеличить уровень компендиума на 50.')
    :SetPrice(499)
    :SetOnBuy(function(self, pl)
      pl:AddCompendiumLevel(50)
    end)

  rp.shop.Add('+100 Уровней', 'compendiumlevelup100')
    :SetCat('Компендиум')
    :SetDesc('Увеличить уровень компендиума на 100.')
    :SetPrice(999)
    :SetOnBuy(function(self, pl)
      pl:AddCompendiumLevel(100)
    end)


rp.shop.Add('Открыть персонажа', 'newcharacter')
  :SetCat('Основное')
  :SetDesc('Вы можете расширить количество доступных персонажей для создания.\nМожно покупать несколько раз')
  :SetPrice(500)
  :SetGetPrice(function(self, pl)
    return ((pl:GetUpgradeCount('newcharacter') + 1) * self.Price)
  end)

rp.shop.Add('Лимит пропов', 'prop_limit_15')
  :SetCat('Основное')
  :SetDesc('Добавлен к вашему лимиту + 15 пропов.\nМожно докупать.')
  :SetPrice(75)
  :SetGetPrice(function(self, pl)
    return ((pl:GetUpgradeCount('prop_limit_15') + 1) * self.Price)
  end)

if (SERVER) then
	local limit = rp.cfg.PropLimit
	hook.Add('PlayerSpawnProp', 'PropUpgrade.PlayerSpawnPropLimit', function(pl)
		local l = limit

  	if pl:IsAdmin() then
      l = l + 5000
    end

		local upgradeCount = pl:GetUpgradeCount('prop_limit_15')
		if (upgradeCount ~= 0) and not pl:IsAdmin() then
			l = l + (15 * upgradeCount)
		end

		if (pl:GetCount('props') >= l) then
			rp.Notify(pl, NOTIFY_ERROR, rp.Term('SboxPropLimit'))
			return false
		end
	end)
end

rp.shop.Add('Advanced Dublicator 2', 'adv_dupe')
  :SetCat('Основное')
  :SetDesc('Даёт доступ к Advanced Dublicator 2 на месяц')
  :SetPrice(320)
  :SetDuration(2629743) -- sec
  :SetStackable(false)

if (SERVER) then
  hook.Add('CanTool', 'AdvDupe.Donate', function(ply, tr, tool)
    if tool == "advdupe2" then
      if ply:HasUpgrade("adv_dupe") then
        return true
      else
        return false
      end
    end
  end)
end


rp.shop.Add('Сменить никнейм', 'changenickname')
  :SetCat('Основное')
  :SetDesc('Позволяет сменить никнейм после покупки.\nСначала купите эту привилегию, а затем смените никнейм командой "/newnick *Новый никнейм*"')
  :SetPrice(250)
  :SetStackable(true)
  :SetOnBuy(function(self, pl)
    pl.canChangeNick = true
  end)

if SERVER then
	hook.Add("PlayerSay", "DonateChangeNickname", function( ply, text )
		if not ply.canChangeNick then return end
		local tbl = string.Split(text, " ")
		if string.lower(tbl[1]) == "/newnick" then
			local name = tbl[2]
			for i = 3, #tbl do
				name = name.." "..tbl[i]
			end

			rp.NotifyAll(NOTIFY_GENERIC, rp.Term('ChangeName'), ply:SteamName(), name)
			rp.data.SetName(ply, name)
			ply:SetNetVar('Name', name)
			ply:SetNVar('Name', name, NETWORK_PROTOCOL_PUBLIC)
			ply.canChangeNick = nil
		end
	end)
end

rp.shop.Add('Собственная модель', 'ownmodel')
  :SetCat('Дорогое')
  :SetDesc('Вы можете заказать себе собственную игровую модель для определенной профессии.\nЦена - договорная. \nНажмите "Купить", чтобы открыть ссылку на группу.')
  :SetPrice(0)
  :SetStackable(true)
  :SetIcon("models/dog.mdl")
  :SetFunction(function(ply)
  	local cmd = "gui.OpenURL('https://vk.me/octopusgmod')"
  	ply:SendLua(cmd)
  end)

rp.shop.Add('Верфигандо - Dare Devil [1 неделя]', 'verf_dareDevil_7')
  :SetCat('Модели')
  :SetDesc('\nНажмите "Купить", чтобы приобрести данный скин.')
  :SetPrice(50)
  :SetIcon("models/bala/rioter_dare_devil_pm.mdl")
  :SetReferencedJob(TEAM_BAN2)
  :SetDuration(604800) -- неделя
  :SetStackable(false)
  :SetNetworked(true)


rp.shop.Add('Своя группировка', 'owngroup')
  :SetCat('Дорогое')
  :SetDesc('Вы можете заказать себе собственную группировку со своими моделями, оружием, ЛОРом.\nЦена - договорная(от 1-й тысячи рублей). \nНажмите "Купить", чтобы открыть ссылку на группу.')
  :SetPrice(0)
  :SetStackable(true)
  :SetFunction(function(ply)
  	local cmd = "gui.OpenURL('https://vk.me/octopusgmod')"
  	ply:SendLua(cmd)
  end)

rp.shop.Add('Личная база', 'owngbase')
  :SetCat('Дорогое')
  :SetDesc('Вы можете заказать себе или своей группировке собственную базу.\nЦена - договорная(от 1-й тысячи рублей, в зависимости от размера и наполненности).\nНажмите "Купить", чтобы открыть ссылку на группу.')
  :SetPrice(0)
  :SetStackable(true)
  :SetFunction(function(ply)
  	local cmd = "gui.OpenURL('https://vk.me/octopusgmod')"
  	ply:SendLua(cmd)
  end)

rp.shop.Add('Заказать РП-событие', 'ownevent')
  :SetCat('Дорогое')
  :SetDesc('Вы можете провести РП-событие по собственному сценарию. В организации события примут участие ивентологи и администраторы сервера.\nЦена - договорная(от 500 рублей в зависимости от сложности события).\nНажмите "Купить", чтобы открыть ссылку на группу.')
  :SetPrice(0)
  :SetStackable(true)
  :SetFunction(function(ply)
  	local cmd = "gui.OpenURL('https://vk.me/octopusgmod')"
  	ply:SendLua(cmd)
  end)

-- rp.shop.Add('Плохой аппетит', 'no_hunger')
--   :SetCat('Основное')
--   :SetDesc('Вам больше не надо кушать.')
--   :SetPrice(1000)
--   :SetStackable(false)
--   :SetNetworked(true)
--   if SERVER then
--   hook.Add("PlayerHasHunger", function(ply)
--     if ply:HasUpgrade('no_hunger') then return false end
--   end)
-- end

-- rp.shop.Add('+10 кг инвентаря', 'invslots')
--   :SetCat('Основное')
--   :SetDesc('Добавляет 10 кг в инвентарь.\nМожно докупать.')
--   :SetPrice(75)
--   :SetOnBuy(function(self, pl)
--     db:Query("SELECT * FROM darkrp_pocketspace WHERE SteamID64 = "..pl:SteamID64()..";", function(result)
--       if result != nil and #result > 0 then 
--         local row = result[1]
--         pl:SetNWInt("pocketinvspace", tonumber(row["space"]) + 10)
--         db:Query("DELETE FROM darkrp_pocketspace WHERE steamid64 = "..pl:SteamID64()..";", function()
--         db:Query("INSERT INTO darkrp_pocketspace VALUES("..pl:SteamID64()..", ".. tonumber(row["space"]) + 10 ..");") end)
--       end
--     end)
--   end)

-- Cash Packs
rp.shop.Add('1,000 монет', '1k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 1,000 монет на твой аккаунт')
  :SetPrice(50)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(1000)
  end)

rp.shop.Add('5,000 монет', '5k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 5,000 монет на твой аккаунт. Экономия 10%')
  :SetPrice(230)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(5000)
  end)

rp.shop.Add('10,000 монет', '10k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 10,000 монет на твой аккаунт. Экономия 15%')
  :SetPrice(450)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(10000)
  end)

rp.shop.Add('20,000 монет', '20k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 20,000 монет на твой аккаунт. Экономия 20%')
  :SetPrice(900)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(20000)
  end)

rp.shop.Add('50,000 монет', '50k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 50,000 монет на твой аккаунт. Экономия 30%')
  :SetPrice(1800)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(50000)
  end)

rp.shop.Add('100,000 монет', '100k_RP_Cash')
  :SetCat('Валюта')
  :SetDesc('Добавляет 100,000 монет на твой аккаунт. Экономия 40% ')
  :SetPrice(3000)
  :SetOnBuy(function(self, pl)
    pl:AddMoney(100000)
  end)

-- Rnks
rp.shop.Add('VIP (1 месяц)', 'vip1mo')
  :SetCat('Привелегии')
  :SetDesc([[
    VIP на 1 месяц
    - VIP Профессии
    - Резервный слот
    - Отключен лимит на професии
    - +2 кг. переносимого веса в рюкзаке 
    - +30 кг. дополнительного веса в хранилище
    - 25% БОНУСНОГО ОПЫТА за всё

    И все остальное, что будет добавлено для VIP-персон в будущем!
  ]])
  :SetPrice(200)
  :SetDuration(2629743) -- sec
  :SetCanBuy(function(self, pl)
    return !pl:IsVIP(), 'Вы уже VIP!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('VIP (1 год)', 'vipforever')
  :SetCat('Привелегии')
  :SetDesc([[
    VIP на год
    - VIP Профессии
    - Резервный слот
    - Отключен лимит на професии
    - +2 кг. переносимого веса в рюкзаке 
    - +30 кг. дополнительного веса в хранилище
    - 25% БОНУСНОГО ОПЫТА за всё

    И все остальное, что будет добавлено для VIP-персон в будущем!
  ]])
  :SetPrice(800)
  :SetDuration(31104000)
  :SetCanBuy(function(self, pl)
    return !pl:IsVIP(), 'Вы уже VIP!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Premium (1 месяц)', 'prem1mo')
  :SetCat('Привелегии')
  :SetDesc([[
    Premium на 1 месяц
    - Premium Профессии
    - Резервный слот
    - Отключен лимит на професии
    - Не теряете деньги после смерти
    - Бонус к Зарплате X2
    - +3 кг. переносимого веса в рюкзаке 
    - +70 кг. дополнительного веса в хранилище
    - 50% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Premium-персон в будущем!
  ]])
  :SetPrice(350)
  :SetDuration(2629743) -- sec
  :SetCanBuy(function(self, pl)
    return !pl:IsPremium(), 'Вы уже Premium!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Premium (1 год)', 'premforever')
  :SetCat('Привелегии')
  :SetDesc([[
    Premium на год
    - Premium Профессии
    - Резервный слот
    - Отключен лимит на професии
    - Не теряете деньги после смерти
    - Бонус к Зарплате X2
    - +3 кг. переносимого веса в рюкзаке 
    - +70 кг. дополнительного веса в хранилище
    - 50% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Premium-персон в будущем!
  ]])
  :SetPrice(1300)
  :SetDuration(31104000)
  :SetCanBuy(function(self, pl)
    return !pl:IsPremium(), 'Вы уже Premium!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Игрок+ (1 месяц)', 'igrokplus1mo')
  :SetCat('Привелегии')
  :SetDesc([[
    Игрок+ на 1 месяц
    - Резервный слот
    - Отключен лимит на професии
    - +1 кг. переносимого веса в рюкзаке 
    - +10 кг. дополнительного веса в хранилище
    - 10% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Игрок+-персон в будущем!
  ]])
  :SetPrice(100)
  :SetDuration(2629743) -- sec
  :SetCanBuy(function(self, pl)
    return !pl:IsIgrokPlus(), 'Вы уже Игрок+!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Игрок+ (1 год)', 'igrokplusforever')
  :SetCat('Привелегии')
  :SetDesc([[
    Игрок+ на год
    - Резервный слот
    - Отключен лимит на професии
    - +1 кг. переносимого веса в рюкзаке 
    - +10 кг. дополнительного веса в хранилище
    - 10% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Игрок+-персон в будущем!
  ]])
  :SetPrice(450)
  :SetDuration(31104000)
  :SetCanBuy(function(self, pl)
    return !pl:IsIgrokPlus(), 'Вы уже Игрок+!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Спонсор (1 месяц)', 'sponsor1mo')
  :SetCat('Привелегии')
  :SetDesc([[
    Сносор на 1 месяц
    - Всё, что входит в Премиум и V.I.P.
    - Резервный слот
    - Отключен лимит на професии
    - +5 кг. переносимого веса в рюкзаке 
    - +120 кг. дополнительного веса в хранилище
    - 100% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Сносор-персон в будущем!
  ]])
  :SetPrice(600)
  :SetDuration(2629743) -- sec
  :SetCanBuy(function(self, pl)
    return !pl:IsSponsor(), 'Вы уже Спонсор!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

rp.shop.Add('Спонсор (1 год)', 'sponsorforever')
  :SetCat('Привелегии')
  :SetDesc([[
    Сносор на год
    - Всё, что входит в Премиум и V.I.P.
    - Резервный слот
    - Отключен лимит на професии
    - +5 кг. переносимого веса в рюкзаке 
    - +120 кг. дополнительного веса в хранилище
    - 100% БОНУСНОГО ОПЫТА за всё.

    И все остальное, что будет добавлено для Сносор-персон в будущем!
  ]])
  :SetPrice(1700)
  :SetDuration(31104000)
  :SetCanBuy(function(self, pl)
    return !pl:IsIgrokPlus(), 'Вы уже спонсор!'
  end)
  :SetOnBuy(function(self, pl)

  end)
  :SetNetworked(true)

-- rp.shop.Add('Пакет - VIP', 'VIP_Package')
--   :SetCat('Привелегии')
--   :SetDesc([[В Пакет входит:
--   + VIP навсегда
--   + 100.000$
  
--   ]])
--   :SetPrice(1000)
--   :SetCanBuy(function(self, pl)
--     return !pl:IsVIP(), 'Вы уже VIP!'
--   end)
--   :SetOnBuy(function(self, pl)
--     pl:AddMoney(100000)
--   end)
--   :SetNetworked(true)

-- -- Оружие навсегда

-- rp.shop.Add('Монтировка', 'perma_crowbar')
--   :SetCat('Оружие навсегда')
--   :SetPrice(50)
--   :SetWeapon('weapon_crowbar')
--   :SetIcon('models/weapons/w_crowbar.mdl')

-- rp.shop.Add('Дубинка', 'perma_stunstick')
--   :SetCat('Оружие навсегда')
--   :SetPrice(50)
--   :SetWeapon('weapon_stunstick')
--   :SetIcon('models/weapons/w_stunbaton.mdl')

-- rp.shop.Add('Кулаки', 'perma_fists')
--   :SetCat('Оружие навсегда')
--   :SetPrice(30)
--   :SetWeapon('hl2_combo_fists')

-- rp.shop.Add('Медицинский Вейп', 'perma_vape')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('weapon_vape_medicinal')
--   :SetStackable(true)
--   :SetIcon('models/vape_pen.mdl')
--   :SetDesc('Вам будет даваться Электронная Сигарета при возрождении.\nОна позволяет вам пускать струи зелёного дыма, пополняя ваше здоровье.')
--   :SetCanBuy(function(self, pl)
--     return pl:GetUpgradeCount(self:GetUID()) < 2, 'Круче некуда.'
--   end)
--   :SetGetPrice(function(self, pl)
--     local cost = 0
--     if pl:HasUpgrade(self:GetUID()) then
--       cost = self.Price * (pl:GetUpgradeCount(self:GetUID()))
--     end
--     return self.Price + cost
--   end)

-- rp.shop.Add('Fiveseven', 'perma_fiveseven')
--   :SetCat('Оружие навсегда')
--   :SetPrice(75)
--   :SetWeapon('swb_fiveseven')
--   :SetIcon('models/weapons/3_pist_fiveseven.mdl')

-- rp.shop.Add('Glock-18', 'perma_glock')
--   :SetCat('Оружие навсегда')
--   :SetPrice(75)
--   :SetWeapon('swb_glock18')
--   :SetIcon('models/weapons/3_pist_glock18.mdl')

-- rp.shop.Add('P228', 'perma_p228')
--   :SetCat('Оружие навсегда')
--   :SetPrice(75)
--   :SetWeapon('swb_p228')
--   :SetIcon('models/weapons/3_pist_p228.mdl')

-- rp.shop.Add('USP .45', 'perma_usp')
--   :SetCat('Оружие навсегда')
--   :SetPrice(75)
--   :SetWeapon('swb_usp')
--   :SetIcon('models/weapons/3_pist_usp.mdl')

-- rp.shop.Add('MP5', 'perma_mp5')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_mp5')
--   :SetIcon('models/weapons/3_smg_mp5.mdl')

-- rp.shop.Add('TMP', 'perma_tmp')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_tmp')
--   :SetIcon('models/weapons/3_smg_tmp.mdl')

-- rp.shop.Add('MAC10', 'perma_mac10')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_mac10')
--   :SetIcon('models/weapons/3_smg_mac10.mdl')

-- rp.shop.Add('UMP', 'perma_ump')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_ump')
--   :SetIcon('models/weapons/3_smg_ump45.mdl')

-- rp.shop.Add('.357 Magnum', 'perma_357')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_357')
--   :SetIcon('models/weapons/w_357.mdl')

-- rp.shop.Add('Desert Eagle', 'perma_deagle')
--   :SetCat('Оружие навсегда')
--   :SetPrice(150)
--   :SetWeapon('swb_deagle')
--   :SetIcon('models/weapons/3_pist_deagle.mdl')

-- rp.shop.Add('AK47', 'perma_ak47')
--   :SetCat('Оружие навсегда')
--   :SetPrice(250)
--   :SetWeapon('swb_ak47')
--   :SetIcon('models/weapons/3_rif_ak47.mdl')

-- rp.shop.Add('M4A1', 'perma_m4a1')
--   :SetCat('Оружие навсегда')
--   :SetPrice(250)
--   :SetWeapon('swb_m4a1')
--   :SetIcon('models/weapons/3_rif_m4a1.mdl')

-- rp.shop.Add('AWP', 'perma_awp')
--   :SetCat('Оружие навсегда')
--   :SetPrice(500)
--   :SetWeapon('swb_awp')
--   :SetIcon('models/weapons/3_snip_awp.mdl')

-- rp.shop.Add('M249', 'perma_m249')
--   :SetCat('Оружие навсегда')
--   :SetPrice(500)
--   :SetWeapon('swb_m249')
--   :SetIcon('models/weapons/3_mach_m249para.mdl')

-- rp.shop.Add('Отмычка', 'lockpick')
--   :SetCat('Оружие навсегда')
--   :SetPrice(100)
--   :SetWeapon('lockpick')
--   :SetIcon('models/weapons/custom/w_lockpick.mdl')
      
-- rp.shop.Add('Взломщик', 'keypad_cracker')
--   :SetCat('Оружие навсегда')
--   :SetPrice(100)
--   :SetWeapon('keypad_cracker')
--   :SetIcon('models/weapons/w_c4.mdl')
  
rp.shop.Add('Боун Крашер', 'time_crasher')
  :SetCat('Временное оружие')
  :SetPrice(80)
  :SetDesc('Вам будет выдаваться Боун Крашер при возрождении в течение 1 недели')
  :SetDuration(604800)
  :SetTimeWeapon('tfa_kf2_mace_job')
  :SetIcon('models/weapons/tfa_kf2/w_shield_mace.mdl')
  :SetStackable(false)

rp.shop.Add('Пожарный топор', 'time_axe')
  :SetCat('Временное оружие')
  :SetPrice(50)
  :SetDesc('Вам будет выдаваться Топор при возрождении в течение 1 недели')
  :SetDuration(604800)
  :SetTimeWeapon('tfa_nmrih_fireaxe_job')
  :SetIcon('models/weapons/tfa_nmrih/w_me_axe_fire.mdl')
  :SetStackable(false)

rp.shop.Add('Молот', 'time_molot')
  :SetCat('Временное оружие')
  :SetPrice(60)
  :SetDesc('Вам будет выдаваться Молот при возрождении в течение 1 недели')
  :SetDuration(604800)
  :SetTimeWeapon('tfa_nmrih_sledge_job')
  :SetIcon('models/weapons/tfa_nmrih/w_me_sledge.mdl')
  :SetStackable(false)

rp.shop.Add('Одноручный топорик', 'time_toporik')
  :SetCat('Временное оружие')
  :SetPrice(50)
  :SetDesc('Вам будет выдаваться Одноручный топорик при возрождении в течение 1 недели')
  :SetDuration(604800)
  :SetTimeWeapon('tfa_nmrih_hatchet_job')
  :SetIcon('models/weapons/tfa_nmrih/w_me_hatchet.mdl')
  :SetStackable(false)

rp.shop.Add('Говорилка', 'time_govorilka')
  :SetCat('Основное')
  :SetPrice(60)
  :SetDesc('Все ваши сообщения в чате будут озвучиваться голосом в течение 1 недели')
  :SetDuration(604800)
  :SetStackable(false)
------------

-- rp.shop.Add('Опытный выживший[Неделя]', 'nabor_opitniyvijivshiy')
--   :SetCat('Наборы')
--   :SetPrice(79)
--   :SetIcon("models/player/backpack_molle/molle.mdl")
--   :SetDesc([[Вы получите доступ к набору "Опытный выживший" на неделю(Клавиша 'F2' - Открыть меню наборов)
	
-- 	Набор опытного выжившего, который успел обжиться припасами.
--   	Вы получите: USP 45, гражданский бронежилет, две пачки патронов, еда, вода, топор, рацию и медицину(много)]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Охотник[Неделя]', 'nabor_ohotnik')
--   :SetCat('Наборы')
--   :SetPrice(99)
--   :SetIcon("models/player/backpack_baselardwild/scavbp.mdl")
--   :SetDesc([[Вы получите доступ к набору "Охотник" на неделю(Клавиша 'F2' - Открыть меню наборов)

--   	Набор охотника, который включает в себя: Сырое мясо, пару банок пива, Raging Bull, военное кепи и охотничью винтовку Winchester.
--   	Также при себе имеет рацию,гитару,бинт и пачку патронов.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Полицейский[Неделя]', 'nabor_police')
--   :SetCat('Наборы')
--   :SetPrice(99)
--   :SetIcon("models/combataegis/body/policevest.mdl")
--   :SetDesc([[Вы получите доступ к набору "Полицейский" на неделю(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор бывшего полицейского, который включает в себя: Полицейский Remington 870 и бронежилет, М1911, пончики и газировку.
--   	Имеет при себе рацию, бронежилет, аптечку и пачку патронов.
--   	]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Мародер[Неделя]', 'nabor_moroder')
--   :SetCat('Наборы')
--   :SetPrice(119)
--   :SetIcon("models/modified/bandana.mdl")
--   :SetDesc([[Вы получите доступ к набору "Мародер" на неделю(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор того,кто готов убивать других ради своего выживания.
--   	Включает в себя UMP 45 и UZI, мотоциклетный шлем и гражданский бронежилет, а также бейсбольную биту, еду и воду и пачку патронов.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Военный[Неделя]', 'nabor_voenniy')
--   :SetCat('Наборы')
--   :SetPrice(119)
--   :SetIcon("models/player/backpack_blackjack/blackjack.mdl")
--   :SetDesc([[Вы получите доступ к набору "Военный" на неделю(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор рядового бойца армии Соединенных Штатов Америки.
--   	Вы получите MP5, USP, тактический бронежилет, военную каску, патроны и монтировку.
--   	Также имеется дневной рацион питания,рация,аптечка.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Крушитель[Неделя]', 'nabor_krushitel')
--   :SetCat('Наборы')
--   :SetPrice(129)
--   :SetIcon("models/combataegis/body/ballisticvest.mdl")
--   :SetDesc([[Вы получите доступ к набору "Крушитель" в течение одной недели(Клавиша 'F2' - Открыть меню наборов)

--   	Набор выжившего, который делает упор на грубую силу. 
--   	Включает в себя огромный фубар, Colt Phyton, тяжелый взрывоустойчивый бронежилет, шлем, патроны и две большие аптечки.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Снайпер[Неделя]', 'nabor_sniper')
--   :SetCat('Наборы')
--   :SetPrice(199)
--   :SetIcon("models/player/backpack_trizip/trizip.mdl")
--   :SetDesc([[Вы получите доступ к набору "Снайпер" на неделю(Клавиша 'F2' - Открыть меню наборов)

--   	Набор снайпера-партизана. 
--   	Включает в себя SVD Dragunov, SIG P223, тактический бронежилет, бинокль, патроны, еду, воду, рацию и нож.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Дитя Апокалипсиса[Неделя]', 'nabor_dityaapocalypsisa')
--   :SetCat('Наборы')
--   :SetPrice(249)
--   :SetIcon("models/player/backpack_pilgrim/pilgrim.mdl")
--   :SetDesc([[Вы получите доступ к набору "Дитя Апокалипсиса" на неделю(Клавиша 'F2' - Открыть меню наборов)

--   	Набор настоящего Дитя Апокалипсиса.
--   	Включает в себя Spas 12, Desert Eagle, MP9, штурмовой шлем, баллистический бронежилет, двуручный топор, 
--   	еду, воду, патроны, рацию, бинокль и антидот.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)

-- --1 mo
-- rp.shop.Add('Опытный выживший[Месяц]', 'nabor_opitniyvijivshiy1mo')
--   :SetCat('Наборы')
--   :SetPrice(149)
--   :SetIcon("models/player/backpack_molle/molle.mdl")
--   :SetDesc([[Вы получите доступ к набору "Опытный выживший" на месяц(Клавиша 'F2' - Открыть меню наборов)
	
-- 	Набор опытного выжившего, который успел обжиться припасами.
--   	Вы получите: USP 45, гражданский бронежилет, две пачки патронов, еда, вода, топор, рацию и медицину(много)]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Охотник[Месяц]', 'nabor_ohotnik1mo')
--   :SetCat('Наборы')
--   :SetPrice(199)
--   :SetIcon("models/player/backpack_baselardwild/scavbp.mdl")
--   :SetDesc([[Вы получите доступ к набору "Охотник" на месяц(Клавиша 'F2' - Открыть меню наборов)

--   	Набор охотника, который включает в себя: Сырое мясо, пару банок пива, Raging Bull, военное кепи и охотничью винтовку Winchester.
--   	Также при себе имеет рацию,гитару,бинт и пачку патронов.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Полицейский[Месяц]', 'nabor_police1mo')
--   :SetCat('Наборы')
--   :SetPrice(199)
--   :SetIcon("models/combataegis/body/policevest.mdl")
--   :SetDesc([[Вы получите доступ к набору "Полицейский" на месяц(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор бывшего полицейского, который включает в себя: Полицейский Remington 870 и бронежилет, М1911, пончики и газировку.
--   	Имеет при себе рацию, бронежилет, аптечку и пачку патронов.
--   	]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Мародер[Месяц]', 'nabor_moroder1mo')
--   :SetCat('Наборы')
--   :SetPrice(239)
--   :SetIcon("models/modified/bandana.mdl")
--   :SetDesc([[Вы получите доступ к набору "Мародер" на месяц(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор того,кто готов убивать других ради своего выживания.
--   	Включает в себя UMP 45 и UZI, мотоциклетный шлем и гражданский бронежилет, а также бейсбольную биту, еду и воду и пачку патронов.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Военный[Месяц]', 'nabor_voenniy1mo')
--   :SetCat('Наборы')
--   :SetPrice(239)
--   :SetIcon("models/player/backpack_blackjack/blackjack.mdl")
--   :SetDesc([[Вы получите доступ к набору "Военный" на месяц(Клавиша 'F2' - Открыть меню наборов)
  	
--   	Набор рядового бойца армии Соединенных Штатов Америки.
--   	Вы получите MP5, USP, тактический бронежилет, военную каску, патроны и монтировку.
--   	Также имеется дневной рацион питания,рация,аптечка.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Крушитель[Месяц]', 'nabor_krushitel1mo')
--   :SetCat('Наборы')
--   :SetPrice(259)
--   :SetIcon("models/combataegis/body/ballisticvest.mdl")
--   :SetDesc([[Вы получите доступ к набору "Крушитель" на месяц(Клавиша 'F2' - Открыть меню наборов)

--   	Набор выжившего, который делает упор на грубую силу. 
--   	Включает в себя огромный фубар, Colt Phyton, тяжелый взрывоустойчивый бронежилет, шлем, патроны и две большие аптечки.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Снайпер[Месяц]', 'nabor_sniper1mo')
--   :SetCat('Наборы')
--   :SetPrice(399)
--   :SetIcon("models/player/backpack_trizip/trizip.mdl")
--   :SetDesc([[Вы получите доступ к набору "Снайпер" на месяц(Клавиша 'F2' - Открыть меню наборов)

--   	Набор снайпера-партизана. 
--   	Включает в себя SVD Dragunov, SIG P223, тактический бронежилет, бинокль, патроны, еду, воду, рацию и нож.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Дитя Апокалипсиса[Месяц]', 'nabor_dityaapocalypsisa1mo')
--   :SetCat('Наборы')
--   :SetPrice(499)
--   :SetIcon("models/player/backpack_pilgrim/pilgrim.mdl")
--   :SetDesc([[Вы получите доступ к набору "Дитя Апокалипсиса" на месяц(Клавиша 'F2' - Открыть меню наборов)

--   	Набор настоящего Дитя Апокалипсиса.
--   	Включает в себя Spas 12, Desert Eagle, MP9, штурмовой шлем, баллистический бронежилет, двуручный топор, 
--   	еду, воду, патроны, рацию, бинокль и антидот.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)

-- rp.shop.Add('Синяя волна [Месяц]', 'weaponskin_bluewave')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_hk_416.mdl")
--   :SetSkin("z_easyskins/camo/blue_wave.vmt")
--   :SetSkinID(8)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Синяя волна.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 8)
--   end)

-- rp.shop.Add('Тёмная материя [Месяц]', 'weaponskin_darkmatter')
--   :SetCat('Скины для оружия')
--   :SetPrice(399)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dark_matter.vmt")
--   :SetSkinID(14)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Тёмная материя.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 14)
--   end)

-- rp.shop.Add('Пульсация [Месяц]', 'weaponskin_ripple')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/ripple.vmt")
--   :SetSkinID(37)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Пульсация.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 37)
--   end)

-- rp.shop.Add('Звёзды [Месяц]', 'weaponskin_stars')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/stars.vmt")
--   :SetSkinID(40)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Звёзды.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 40)
--   end)

-- rp.shop.Add('Пульсация материи [Месяц]', 'weaponskin_darkpulse')
--   :SetCat('Скины для оружия')
--   :SetPrice(600)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dark_pulse.vmt")
--   :SetSkinID(15)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Пульсация материи.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 15)
--   end)

-- rp.shop.Add('Голограмма [Месяц]', 'weaponskin_holo')
--   :SetCat('Скины для оружия')
--   :SetPrice(399)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/holo.vmt")
--   :SetSkinID(33)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Голограмма.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 33)
--   end)

-- rp.shop.Add('Плазма [Месяц]', 'weaponskin_dragon')
--   :SetCat('Скины для оружия')
--   :SetPrice(600)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dragon.vmt")
--   :SetSkinID(22)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Плазма.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 22)
--   end)

-- rp.shop.Add('Золотая материя [Месяц]', 'weaponskin_goldmatter')
--   :SetCat('Скины для оружия')
--   :SetPrice(999)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/gold_matter.vmt")
--   :SetSkinID(30)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Золотая материя.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 30)
--   end)

-- rp.shop.Add('Чёрная дыра [Месяц]', 'weaponskin_blackhole')
--   :SetCat('Скины для оружия')
--   :SetPrice(499)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/blackhole.vmt")
--   :SetSkinID(4)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Золотая материя.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 4)
--   end)

-- rp.shop.Add('Манго [Месяц]', 'weaponskin_mango')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/mango.vmt")
--   :SetSkinID(35)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Манго.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 35)
--   end)

-- rp.shop.Add('Kawai [Месяц]', 'weaponskin_kawai')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/kawai.vmt")
--   :SetSkinID(34)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Kawai.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 34)
--   end)

-- rp.shop.Add('Граффити [Месяц]', 'weaponskin_graffiti')
--   :SetCat('Скины для оружия')
--   :SetPrice(199)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/graffiti.vmt")
--   :SetSkinID(31)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Граффити.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 31)
--   end)

-- rp.shop.Add('Резня [Месяц]', 'weaponskin_massacre')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/massacre.vmt")
--   :SetSkinID(36)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Резня.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 36)
--   end)

-- rp.shop.Add('Ронин [Месяц]', 'weaponskin_ronin')
--   :SetCat('Скины для оружия')
--   :SetPrice(199)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/ronin.vmt")
--   :SetSkinID(38)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Ронин.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 38)
--   end)

-- rp.shop.Add('Городской камуфляж [Месяц]', 'weaponskin_urban')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/urban.vmt")
--   :SetSkinID(44)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Городской камуфляж.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 44)
--   end)

-- rp.shop.Add('Травка [Месяц]', 'weaponskin_weed')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/weed.vmt")
--   :SetSkinID(45)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Травка.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 45)
--   end)

-- rp.shop.Add('Электросхема [Месяц]', 'weaponskin_wired')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/wired.vmt")
--   :SetSkinID(46)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Электросхема.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 46)
--   end)

-- rp.shop.Add('Песчаный камуфляж [Месяц]', 'weaponskin_sahara')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/sahara.vmt")
--   :SetSkinID(39)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Песчаный камуфляж.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 39)
--   end)

-- rp.shop.Add('Камуфляж [Месяц]', 'weaponskin_woodland')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/woodland.vmt")
--   :SetSkinID(47)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 47)
--   end)

-- rp.shop.Add('Призрак [Месяц]', 'weaponskin_eliteghost')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/elite_ghost.vmt")
--   :SetSkinID(24)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Призрак.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 24)
--   end)

-- rp.shop.Add('Кровавая маскировка [Месяц]', 'weaponskin_bloodshot')
--   :SetCat('Скины для оружия')
--   :SetPrice(199)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/bloodshot.vmt")
--   :SetSkinID(7)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Кровавая маскировка.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 7)
--   end)

-- rp.shop.Add('Ржавчина [Месяц]', 'weaponskin_breach')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/breach.vmt")
--   :SetSkinID(9)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Ржавчина.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 9)
--   end)

-- rp.shop.Add('Хайтек [Месяц]', 'weaponskin_blackops')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/blackops.vmt")
--   :SetSkinID(5)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Хайтек.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 5)
--   end)

-- rp.shop.Add('Военный камуфляж [Месяц]', 'weaponskin_atacks')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/atacs.vmt")
--   :SetSkinID(2)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Военный камуфляж.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 2)
--   end)

-- rp.shop.Add('Бекон [Месяц]', 'weaponskin_bacon')
--   :SetCat('Скины для оружия')
--   :SetPrice(199)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/bacon.vmt")
--   :SetSkinID(3)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Бекон.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 3)
--   end)

-- rp.shop.Add('Комикс [Месяц]', 'weaponskin_comic')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/comic.vmt")
--   :SetSkinID(11)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Комикс.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 11)
--   end)

-- rp.shop.Add('Зебра [Месяц]', 'weaponskin_craze')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/craze.vmt")
--   :SetSkinID(13)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Зебра.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 13)
--   end)

-- rp.shop.Add('Алмаз [Месяц]', 'weaponskin_diamond')
--   :SetCat('Скины для оружия')
--   :SetPrice(699)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/diamond.vmt")
--   :SetSkinID(19)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Алмаз.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 19)
--   end)

-- rp.shop.Add('Камуфляж Digital [Месяц]', 'weaponskin_digital')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/digital.vmt")
--   :SetSkinID(20)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж Digital.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 20)
--   end)

-- rp.shop.Add('$$$ [Месяц]', 'weaponskin_dollars')
--   :SetCat('Скины для оружия')
--   :SetPrice(499)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dollars.vmt")
--   :SetSkinID(21)
--   :SetDesc([[Открывает доступ к скину для всего оружия: $$$.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 21)
--   end)

-- rp.shop.Add('Койот [Месяц]', 'weaponskin_coyote')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/coyote.vmt")
--   :SetSkinID(12)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Койот.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 12)
--   end)

-- rp.shop.Add('Камуфляж Devgri [Месяц]', 'weaponskin_devgru')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/devgru.vmt")
--   :SetSkinID(18)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж Devgri.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 18)
--   end)

-- rp.shop.Add('Хипстер [Месяц]', 'weaponskin_dayofdead')
--   :SetCat('Скины для оружия')
--   :SetPrice(399)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dayofdead.vmt")
--   :SetSkinID(16)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Хипстер.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 16)
--   end)

-- rp.shop.Add('Басилиск [Месяц]', 'weaponskin_derriese')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/der_riese.vmt")
--   :SetSkinID(17)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Басилиск.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 17)
--   end)

-- rp.shop.Add('Цветная зебра [Месяц]', 'weaponskin_zebracolor')
--   :SetCat('Скины для оружия')
--   :SetPrice(399)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/zebra.vmt")
--   :SetSkinID(48)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Цветная зебра.]])
--   :SetDuration(2629743)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 48)
--   end)

--   -- week
-- rp.shop.Add('Синяя волна [Неделя]', 'weaponskin_bluewave')
--   :SetCat('Скины для оружия')
--   :SetPrice(99)
--   :SetIcon("models/weapons/tfa_w_hk_416.mdl")
--   :SetSkin("z_easyskins/camo/blue_wave.vmt")
--   :SetSkinID(8)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Синяя волна.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 8)
--   end)

-- rp.shop.Add('Тёмная материя [Неделя]', 'weaponskin_darkmatter')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dark_matter.vmt")
--   :SetSkinID(14)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Тёмная материя.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 14)
--   end)

-- rp.shop.Add('Пульсация [Неделя]', 'weaponskin_ripple')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/ripple.vmt")
--   :SetSkinID(37)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Пульсация.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 37)
--   end)

-- rp.shop.Add('Звёзды [Неделя]', 'weaponskin_stars')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/stars.vmt")
--   :SetSkinID(40)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Звёзды.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 40)
--   end)

-- rp.shop.Add('Пульсация материи [Неделя]', 'weaponskin_darkpulse')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dark_pulse.vmt")
--   :SetSkinID(15)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Пульсация материи.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 15)
--   end)

-- rp.shop.Add('Голограмма [Неделя]', 'weaponskin_holo')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/holo.vmt")
--   :SetSkinID(33)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Голограмма.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 33)
--   end)

-- rp.shop.Add('Плазма [Неделя]', 'weaponskin_dragon')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dragon.vmt")
--   :SetSkinID(22)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Плазма.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 22)
--   end)

-- rp.shop.Add('Чёрная дыра [Неделя]', 'weaponskin_blackhole')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/blackhole.vmt")
--   :SetSkinID(4)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Золотая материя.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 4)
--   end)

-- rp.shop.Add('Манго [Неделя]', 'weaponskin_mango')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/mango.vmt")
--   :SetSkinID(35)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Манго.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 35)
--   end)

-- rp.shop.Add('Kawai [Неделя]', 'weaponskin_kawai')
--   :SetCat('Скины для оружия')
--   :SetPrice(100)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/kawai.vmt")
--   :SetSkinID(34)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Kawai.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 34)
--   end)

-- rp.shop.Add('Граффити [Неделя]', 'weaponskin_graffiti')
--   :SetCat('Скины для оружия')
--   :SetPrice(80)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/graffiti.vmt")
--   :SetSkinID(31)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Граффити.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 31)
--   end)

-- rp.shop.Add('Резня [Неделя]', 'weaponskin_massacre')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/massacre.vmt")
--   :SetSkinID(36)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Резня.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 36)
--   end)

-- rp.shop.Add('Ронин [Неделя]', 'weaponskin_ronin')
--   :SetCat('Скины для оружия')
--   :SetPrice(80)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/ronin.vmt")
--   :SetSkinID(38)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Ронин.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 38)
--   end)

-- rp.shop.Add('Городской камуфляж [Неделя]', 'weaponskin_urban')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/urban.vmt")
--   :SetSkinID(44)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Городской камуфляж.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 44)
--   end)

-- rp.shop.Add('Травка [Неделя]', 'weaponskin_weed')
--   :SetCat('Скины для оружия')
--   :SetPrice(100)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/weed.vmt")
--   :SetSkinID(45)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Травка.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 45)
--   end)

-- rp.shop.Add('Электросхема [Неделя]', 'weaponskin_wired')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/wired.vmt")
--   :SetSkinID(46)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Электросхема.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 46)
--   end)

-- rp.shop.Add('Песчаный камуфляж [Неделя]', 'weaponskin_sahara')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/sahara.vmt")
--   :SetSkinID(39)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Песчаный камуфляж.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 39)
--   end)

-- rp.shop.Add('Камуфляж [Неделя]', 'weaponskin_woodland')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/woodland.vmt")
--   :SetSkinID(47)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 47)
--   end)

-- rp.shop.Add('Призрак [Неделя]', 'weaponskin_eliteghost')
--   :SetCat('Скины для оружия')
--   :SetPrice(100)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/elite_ghost.vmt")
--   :SetSkinID(24)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Призрак.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 24)
--   end)

-- rp.shop.Add('Кровавая маскировка [Неделя]', 'weaponskin_bloodshot')
--   :SetCat('Скины для оружия')
--   :SetPrice(80)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/bloodshot.vmt")
--   :SetSkinID(7)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Кровавая маскировка.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 7)
--   end)

-- rp.shop.Add('Ржавчина [Неделя]', 'weaponskin_breach')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/breach.vmt")
--   :SetSkinID(9)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Ржавчина.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 9)
--   end)

-- rp.shop.Add('Хайтек [Неделя]', 'weaponskin_blackops')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/blackops.vmt")
--   :SetSkinID(5)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Хайтек.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 5)
--   end)

-- rp.shop.Add('Военный камуфляж [Неделя]', 'weaponskin_atacks')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/atacs.vmt")
--   :SetSkinID(2)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Военный камуфляж.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 2)
--   end)

-- rp.shop.Add('Бекон [Неделя]', 'weaponskin_bacon')
--   :SetCat('Скины для оружия')
--   :SetPrice(80)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/bacon.vmt")
--   :SetSkinID(3)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Бекон.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 3)
--   end)

-- rp.shop.Add('Комикс [Неделя]', 'weaponskin_comic')
--   :SetCat('Скины для оружия')
--   :SetPrice(100)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/comic.vmt")
--   :SetSkinID(11)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Комикс.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 11)
--   end)

-- rp.shop.Add('Зебра [Неделя]', 'weaponskin_craze')
--   :SetCat('Скины для оружия')
--   :SetPrice(100)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/craze.vmt")
--   :SetSkinID(13)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Зебра.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 13)
--   end)

-- rp.shop.Add('Алмаз [Неделя]', 'weaponskin_diamond')
--   :SetCat('Скины для оружия')
--   :SetPrice(249)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/diamond.vmt")
--   :SetSkinID(19)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Алмаз.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 19)
--   end)

-- rp.shop.Add('Камуфляж Digital [Неделя]', 'weaponskin_digital')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/digital.vmt")
--   :SetSkinID(20)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж Digital.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 20)
--   end)

-- rp.shop.Add('$$$ [Неделя]', 'weaponskin_dollars')
--   :SetCat('Скины для оружия')
--   :SetPrice(199)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dollars.vmt")
--   :SetSkinID(21)
--   :SetDesc([[Открывает доступ к скину для всего оружия: $$$.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 21)
--   end)

-- rp.shop.Add('Койот [Неделя]', 'weaponskin_coyote')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/coyote.vmt")
--   :SetSkinID(12)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Койот.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 12)
--   end)

-- rp.shop.Add('Камуфляж Devgri [Неделя]', 'weaponskin_devgru')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/devgru.vmt")
--   :SetSkinID(18)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Камуфляж Devgri.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 18)
--   end)

-- rp.shop.Add('Хипстер [Неделя]', 'weaponskin_dayofdead')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/dayofdead.vmt")
--   :SetSkinID(16)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Хипстер.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 16)
--   end)

-- rp.shop.Add('Басилиск [Неделя]', 'weaponskin_derriese')
--   :SetCat('Скины для оружия')
--   :SetPrice(50)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/der_riese.vmt")
--   :SetSkinID(17)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Басилиск.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 17)
--   end)

-- rp.shop.Add('Цветная зебра [Неделя]', 'weaponskin_zebracolor')
--   :SetCat('Скины для оружия')
--   :SetPrice(149)
--   :SetIcon("models/weapons/tfa_w_masada_acr.mdl")
--   :SetSkin("z_easyskins/camo/zebra.vmt")
--   :SetSkinID(48)
--   :SetDesc([[Открывает доступ к скину для всего оружия: Цветная зебра.]])
--   :SetDuration(604800)
--   :SetStackable(false)
--   :SetNetworked(true)
--   :SetOnBuy(function(self, pl)
--     SV_EASYSKINS.AddSkinDonate(pl, 48)
--   end)
hook.Call('rp.AddUpgrades', GAMEMODE)
