ENT.Base 			= "npc_vj_lnr_maleinfectedbase" 
ENT.Type 			= "ai"
ENT.PrintName 		= "Main Male Infected"
ENT.Author 			= "Darkborn & King of Pootis"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "To create an outbreak!"
ENT.Instructions 	= "You've Been Infected...I'm terribly sorry.."
ENT.Category		= "LNR"
