VManip:RegisterAnim("interactslower",
{
["model"]="c_vmanipinteract.mdl",
["lerp_peak"]=0.7,
["lerp_speed_in"]=1,
["lerp_speed_out"]=0.8,
["lerp_curve"]=2.5,
["speed"]=1,
["startcycle"]=0,
["sounds"]={},
["loop"]=false
}
)